[PHP]
post_max_size = 2048M
upload_max_filesize = 2048M
max_execution_time=1800
max_input_time=-1
memory_limit=8192M
max_input_vars=10000
variables_order = EGPCS
default_socket_timeout=1800

; [soap]
; extension=soap
; soap.wsdl_cache_enabled=1
; soap.wsdl_cache_dir="/tmp"
; soap.wsdl_cache_ttl=86400
; soap.wsdl_cache_limit=5
