[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
loglevel=info

[unix_http_server]
file=/var/run/supervisor.sock
chmod=0700

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[include]
files = /etc/supervisord.d/*.conf

[program:frankenphp]
command=/usr/local/bin/frankenphp php-server --listen :80 --root /var/www/app/public
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/frankenphp.log
stderr_logfile=/var/log/supervisor/frankenphp_error.log
priority=1

[program:laravel-schedule]
command=docker-php-entrypoint php artisan schedule:work
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/schedule.log
stderr_logfile=/var/log/supervisor/schedule_error.log
user=root
priority=2

[program:horizon]
command=docker-php-entrypoint php artisan horizon
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=root
redirect_stderr=true
stdout_logfile=/var/www/app/horizon.log
stopwaitsecs=3600
priority=3

[program:pulse-check]
command=docker-php-entrypoint php artisan pulse:check
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/pulse-check.log
stderr_logfile=/var/log/supervisor/pulse-check_error.log
user=root
priority=6

