[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[unix_http_server]
file=/run/supervisord.sock
chmod=0700

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///run/supervisord.sock

[program:php]
command=%(ENV_SUPERVISOR_PHP_COMMAND)s
user=%(ENV_SUPERVISOR_PHP_USER)s
environment=LARAVEL_SAIL="1"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=1

[program:laravel-schedule]
command=/usr/local/bin/php /var/www/html/artisan schedule:work
user=%(ENV_SUPERVISOR_PHP_USER)s
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/schedule.log
stderr_logfile=/var/log/supervisor/schedule_error.log
priority=2

[program:horizon]
command=/usr/local/bin/php /var/www/html/artisan horizon
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=%(ENV_SUPERVISOR_PHP_USER)s
redirect_stderr=true
stdout_logfile=/var/log/supervisor/horizon.log
stopwaitsecs=3600
priority=3

[program:pulse-check]
command=/usr/local/bin/php /var/www/html/artisan pulse:check
user=%(ENV_SUPERVISOR_PHP_USER)s
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/pulse-check.log
stderr_logfile=/var/log/supervisor/pulse-check_error.log
priority=6
